// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cadastroTalentos.Infrastructure.Persistence;

#nullable disable

namespace cadastroTalentos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CadastroTalentosDbContext))]
    [Migration("20261002195841_AdicionarOrigemAvaliacao")]
    partial class AdicionarOrigemAvaliacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cadastroTalentos.Core.Entities.AvaliacaoCandidato", b =>
                {
                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comentario")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<byte>("NotaComunicacao")
                        .HasColumnType("tinyint");

                    b.Property<byte>("NotaExperiencia")
                        .HasColumnType("tinyint");

                    b.Property<byte>("NotaFormacao")
                        .HasColumnType("tinyint");

                    b.Property<bool>("SugeridaPorIa")
                        .HasColumnType("bit");

                    b.HasKey("CandidatoId");

                    b.ToTable("AvaliacoesCandidato", null, t =>
                        {
                            t.HasCheckConstraint("CK_AvaliacoesCandidato_NotaComunicacao", "[NotaComunicacao] BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_AvaliacoesCandidato_NotaExperiencia", "[NotaExperiencia] BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_AvaliacoesCandidato_NotaFormacao", "[NotaFormacao] BETWEEN 0 AND 10");
                        });
                });

            modelBuilder.Entity("cadastroTalentos.Core.Entities.Candidato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<bool>("DataNascimentoEstimada")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OrigemCadastro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sobre")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Candidatos", (string)null);
                });

            modelBuilder.Entity("cadastroTalentos.Core.Entities.Competencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nivel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.ToTable("Competencias", (string)null);
                });

            modelBuilder.Entity("cadastroTalentos.Core.Entities.CurriculoCandidato", b =>
                {
                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChaveArmazenamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoConteudo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CandidatoId");

                    b.HasIndex("ChaveArmazenamento")
                        .IsUnique();

                    b.ToTable("CurriculosCandidato", (string)null);
                });

            modelBuilder.Entity("cadastroTalentos.Core.Entities.ExperienciaProfissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EmpregoAtual")
                        .HasColumnType("bit");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.ToTable("ExperienciasProfissionais", (string)null);
                });

            modelBuilder.Entity("cadastroTalentos.Core.Entities.FormacaoAcademica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Curso")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("DataConclusao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date");

                    b.Property<bool>("EmAndamento")
                        .HasColumnType("bit");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.ToTable("FormacoesAcademicas", (string)null);
                });

            modelBuilder.Entity("cadastroTalentos.Core.Entities.AvaliacaoCandidato", b =>
                {
                    b.HasOne("cadastroTalentos.Core.Entities.Candidato", null)
                        .WithOne("Avaliacao")
                        .HasForeignKey("cadastroTalentos.Core.Entities.AvaliacaoCandidato", "CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("cadastroTalentos.Core.Entities.Competencia", b =>
                {
                    b.HasOne("cadastroTalentos.Core.Entities.Candidato", null)
                        .WithMany("Competencias")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("cadastroTalentos.Core.Entities.CurriculoCandidato", b =>
                {
                    b.HasOne("cadastroTalentos.Core.Entities.Candidato", null)
                        .WithOne("Curriculo")
                        .HasForeignKey("cadastroTalentos.Core.Entities.CurriculoCandidato", "CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("cadastroTalentos.Core.Entities.ExperienciaProfissional", b =>
                {
                    b.HasOne("cadastroTalentos.Core.Entities.Candidato", null)
                        .WithMany("Experiencias")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("cadastroTalentos.Core.Entities.FormacaoAcademica", b =>
                {
                    b.HasOne("cadastroTalentos.Core.Entities.Candidato", null)
                        .WithMany("Formacoes")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("cadastroTalentos.Core.Entities.Candidato", b =>
                {
                    b.Navigation("Avaliacao");

                    b.Navigation("Competencias");

                    b.Navigation("Curriculo");

                    b.Navigation("Experiencias");

                    b.Navigation("Formacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
